"""empty message

Revision ID: 6a4a7a79947a
Revises: e718b4641a07
Create Date: 2024-03-01 17:53:30.339004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4a7a79947a'
down_revision = 'e718b4641a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outtake_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outtake_transaction', schema=None) as batch_op:
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
