"""empty message

Revision ID: b558b38a02cb
Revises: 506c62e2c8ff
Create Date: 2024-03-01 04:45:37.666955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b558b38a02cb'
down_revision = '506c62e2c8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('donor_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_info', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user')

    # ### end Alembic commands ###
