"""empty message

Revision ID: cd455d1352e1
Revises: b558b38a02cb
Create Date: 2024-03-01 04:55:34.587013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd455d1352e1'
down_revision = 'b558b38a02cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_info', sa.String(), nullable=True))

    with op.batch_alter_table('outtake_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_info', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outtake_transaction', schema=None) as batch_op:
        batch_op.drop_column('donor_info')

    with op.batch_alter_table('intake_transaction', schema=None) as batch_op:
        batch_op.drop_column('donor_info')

    # ### end Alembic commands ###
